package recipesearch;

import javax.swing.BorderFactory;
import javax.swing.JRadioButton;
import javax.swing.border.BevelBorder;
import javax.swing.border.Border;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

public class RecipeSearchView extends javax.swing.JFrame {

    /**
     * Creates new form ExampleApplicationView
     */
    public RecipeSearchView() {
        initComponents();
        lastClickedRadioButton = noMainRadioButton;
        meatRadioButton.setBorder(standardBorder);
        vegetarianRadioButton.setBorder(standardBorder);
        chickenRadioButton.setBorder(standardBorder);
        fishRadioButton.setBorder(standardBorder);
        noMainRadioButton.setBorder(clickedBorder);
        noMainRadioButton.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainIngredientButtonGroup = new javax.swing.ButtonGroup();
        difficulityButtonGroup = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cuisineComboBox = new javax.swing.JComboBox();
        meatRadioButton = new javax.swing.JRadioButton();
        fishRadioButton = new javax.swing.JRadioButton();
        vegetarianRadioButton = new javax.swing.JRadioButton();
        chickenRadioButton = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        easyRadioButton = new javax.swing.JRadioButton();
        mediumRadioButton = new javax.swing.JRadioButton();
        hardRadioButton = new javax.swing.JRadioButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        maxPriceSpinner = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        maxTimeSpinner = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        noMainRadioButton = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("recipesearch/resources/RecipeSearch"); // NOI18N
        setTitle(bundle.getString("Application.title")); // NOI18N
        setName("applicationFrame"); // NOI18N

        jSplitPane1.setDividerLocation(160);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sök");

        cuisineComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cuisineComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuisineComboBoxActionPerformed(evt);
            }
        });

        mainIngredientButtonGroup.add(meatRadioButton);
        meatRadioButton.setText("Kött");
        meatRadioButton.setBorder(null);
        meatRadioButton.setBorderPainted(true);
        meatRadioButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recipesearch/resources/meat_icon.png"))); // NOI18N
        meatRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                meatRadioButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                meatRadioButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                meatRadioButtonMouseExited(evt);
            }
        });

        mainIngredientButtonGroup.add(fishRadioButton);
        fishRadioButton.setText("Fisk");
        fishRadioButton.setBorder(null);
        fishRadioButton.setBorderPainted(true);
        fishRadioButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recipesearch/resources/fish_icon.png"))); // NOI18N
        fishRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fishRadioButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fishRadioButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fishRadioButtonMouseExited(evt);
            }
        });

        mainIngredientButtonGroup.add(vegetarianRadioButton);
        vegetarianRadioButton.setText("Vegteriskt");
        vegetarianRadioButton.setBorder(null);
        vegetarianRadioButton.setBorderPainted(true);
        vegetarianRadioButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recipesearch/resources/tree_icon.png"))); // NOI18N
        vegetarianRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vegetarianRadioButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                vegetarianRadioButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                vegetarianRadioButtonMouseExited(evt);
            }
        });

        mainIngredientButtonGroup.add(chickenRadioButton);
        chickenRadioButton.setText("Kyckling");
        chickenRadioButton.setBorder(null);
        chickenRadioButton.setBorderPainted(true);
        chickenRadioButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recipesearch/resources/Chicken_icon.png"))); // NOI18N
        chickenRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chickenRadioButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                chickenRadioButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                chickenRadioButtonMouseExited(evt);
            }
        });

        jLabel2.setText("Kök");

        difficulityButtonGroup.add(easyRadioButton);
        easyRadioButton.setText("Lätt");

        difficulityButtonGroup.add(mediumRadioButton);
        mediumRadioButton.setText("Medel");

        difficulityButtonGroup.add(hardRadioButton);
        hardRadioButton.setText("Svårt");

        jLabel3.setText("Max Pris");

        jLabel4.setText("Max Tid");

        jLabel5.setText("Huvudingrediens");

        jLabel6.setText("Svårighetsgrad");

        mainIngredientButtonGroup.add(noMainRadioButton);
        noMainRadioButton.setText("Ej valt");
        noMainRadioButton.setBorder(null);
        noMainRadioButton.setBorderPainted(true);
        noMainRadioButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recipesearch/resources/no_choice.png"))); // NOI18N
        noMainRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noMainRadioButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                noMainRadioButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                noMainRadioButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(cuisineComboBox, 0, 93, Short.MAX_VALUE)
                                .addGap(42, 42, 42))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(65, 65, 65))
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addComponent(jSeparator2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(maxTimeSpinner))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(maxPriceSpinner)))
                        .addGap(12, 12, 12))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hardRadioButton)
                            .addComponent(mediumRadioButton)
                            .addComponent(easyRadioButton)
                            .addComponent(jLabel6)
                            .addComponent(vegetarianRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(meatRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chickenRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fishRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(noMainRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cuisineComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(meatRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vegetarianRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chickenRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fishRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noMainRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(8, 8, 8)
                .addComponent(easyRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mediumRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hardRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(maxPriceSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(maxTimeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel2);

        java.util.ResourceBundle bundle1 = java.util.ResourceBundle.getBundle("recipesearch/resources/RecipeSearchView"); // NOI18N
        fileMenu.setText(bundle1.getString("fileMenu.text")); // NOI18N

        exitMenuItem.setText(bundle1.getString("exitApplicationMenuItem.text")); // NOI18N
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        jMenuBar1.add(fileMenu);

        helpMenu.setText(bundle1.getString("helpMenu.text")); // NOI18N

        aboutMenuItem.setText(bundle1.getString("aboutMenuItem.text")); // NOI18N
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        new RecipeSearchAboutBox(this).setVisible(true);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void cuisineComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuisineComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuisineComboBoxActionPerformed

    private void chickenRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chickenRadioButtonMouseClicked
        setActiveMainIngredientRadioButton(chickenRadioButton);
    }//GEN-LAST:event_chickenRadioButtonMouseClicked

    private void vegetarianRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vegetarianRadioButtonMouseClicked
        setActiveMainIngredientRadioButton(vegetarianRadioButton);
    }//GEN-LAST:event_vegetarianRadioButtonMouseClicked

    private void meatRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_meatRadioButtonMouseClicked
        setActiveMainIngredientRadioButton(meatRadioButton);
    }//GEN-LAST:event_meatRadioButtonMouseClicked

    private void fishRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fishRadioButtonMouseClicked
        setActiveMainIngredientRadioButton(fishRadioButton);
    }//GEN-LAST:event_fishRadioButtonMouseClicked

    private void noMainRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noMainRadioButtonMouseClicked
        setActiveMainIngredientRadioButton(noMainRadioButton);
    }//GEN-LAST:event_noMainRadioButtonMouseClicked

    private void meatRadioButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_meatRadioButtonMouseEntered
        setMouseOverRadioButton(meatRadioButton);
    }//GEN-LAST:event_meatRadioButtonMouseEntered

    private void vegetarianRadioButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vegetarianRadioButtonMouseEntered
        setMouseOverRadioButton(vegetarianRadioButton);
    }//GEN-LAST:event_vegetarianRadioButtonMouseEntered

    private void chickenRadioButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chickenRadioButtonMouseEntered
        setMouseOverRadioButton(chickenRadioButton);
    }//GEN-LAST:event_chickenRadioButtonMouseEntered

    private void fishRadioButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fishRadioButtonMouseEntered
        setMouseOverRadioButton(fishRadioButton);
    }//GEN-LAST:event_fishRadioButtonMouseEntered

    private void noMainRadioButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noMainRadioButtonMouseEntered
        setMouseOverRadioButton(noMainRadioButton);
    }//GEN-LAST:event_noMainRadioButtonMouseEntered

    private void meatRadioButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_meatRadioButtonMouseExited
        removeMouseOverRadioButton(meatRadioButton);
    }//GEN-LAST:event_meatRadioButtonMouseExited

    private void vegetarianRadioButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vegetarianRadioButtonMouseExited
        removeMouseOverRadioButton(vegetarianRadioButton);
    }//GEN-LAST:event_vegetarianRadioButtonMouseExited

    private void chickenRadioButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chickenRadioButtonMouseExited
        removeMouseOverRadioButton(chickenRadioButton);
    }//GEN-LAST:event_chickenRadioButtonMouseExited

    private void fishRadioButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fishRadioButtonMouseExited
        removeMouseOverRadioButton(fishRadioButton);
    }//GEN-LAST:event_fishRadioButtonMouseExited

    private void noMainRadioButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noMainRadioButtonMouseExited
        removeMouseOverRadioButton(noMainRadioButton);
    }//GEN-LAST:event_noMainRadioButtonMouseExited

    private void removeMouseOverRadioButton(JRadioButton btn) {
        if (btn == lastClickedRadioButton)
            return;
        btn.setBorder(standardBorder);
    }
    
    private void setMouseOverRadioButton(JRadioButton btn) {
        if (btn == lastClickedRadioButton)
            return;
        btn.setBorder(mouseOverBorder);
    }
    
    private void setActiveMainIngredientRadioButton(JRadioButton btn) {
        lastClickedRadioButton.setBorder(standardBorder);
        lastClickedRadioButton = btn;
        btn.setBorder(clickedBorder);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JRadioButton chickenRadioButton;
    private javax.swing.JComboBox cuisineComboBox;
    private javax.swing.ButtonGroup difficulityButtonGroup;
    private javax.swing.JRadioButton easyRadioButton;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JRadioButton fishRadioButton;
    private javax.swing.JRadioButton hardRadioButton;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.ButtonGroup mainIngredientButtonGroup;
    private javax.swing.JSpinner maxPriceSpinner;
    private javax.swing.JSpinner maxTimeSpinner;
    private javax.swing.JRadioButton meatRadioButton;
    private javax.swing.JRadioButton mediumRadioButton;
    private javax.swing.JRadioButton noMainRadioButton;
    private javax.swing.JRadioButton vegetarianRadioButton;
    // End of variables declaration//GEN-END:variables
    private JRadioButton lastClickedRadioButton;
    private Border standardBorder = BorderFactory.createBevelBorder(BevelBorder.RAISED, java.awt.Color.white, new java.awt.Color(204, 204, 204), java.awt.Color.lightGray, java.awt.Color.darkGray);
    private Border mouseOverBorder = BorderFactory.createBevelBorder(BevelBorder.RAISED, java.awt.Color.GRAY, new java.awt.Color(250, 250, 250), java.awt.Color.lightGray, java.awt.Color.darkGray);
    private Border clickedBorder = BorderFactory.createBevelBorder(BevelBorder.LOWERED, java.awt.Color.white, new java.awt.Color(204, 204, 204), java.awt.Color.lightGray, java.awt.Color.darkGray);
}
