package recipesearch;

import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JRadioButton;
import javax.swing.border.BevelBorder;
import javax.swing.border.Border;
import se.chalmers.ait.dat215.lab2.Recipe;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

public class RecipeSearchView extends javax.swing.JFrame {

    /**
     * Creates new form ExampleApplicationView
     */
    public RecipeSearchView(IRecipeSearchInputs recipeSearchInputs) {
		this.recipeSearchInputs = recipeSearchInputs;
		
        initComponents();
		
        lastClickedRadioButton = noMainRadioButton;
        meatRadioButton.setBorder(standardBorder);
        vegetarianRadioButton.setBorder(standardBorder);
        chickenRadioButton.setBorder(standardBorder);
        fishRadioButton.setBorder(standardBorder);
        noMainRadioButton.setBorder(clickedBorder);
        noMainRadioButton.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainIngredientButtonGroup = new javax.swing.ButtonGroup();
        difficulityButtonGroup = new javax.swing.ButtonGroup();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cuisineComboBox = new javax.swing.JComboBox();
        meatRadioButton = new javax.swing.JRadioButton();
        fishRadioButton = new javax.swing.JRadioButton();
        vegetarianRadioButton = new javax.swing.JRadioButton();
        chickenRadioButton = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        easyRadioButton = new javax.swing.JRadioButton();
        mediumRadioButton = new javax.swing.JRadioButton();
        hardRadioButton = new javax.swing.JRadioButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        maxPriceSpinner = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        maxTimeSpinner = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        noMainRadioButton = new javax.swing.JRadioButton();
        noDifficulityRadioButton = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        recipeScrollPane = new javax.swing.JScrollPane();
        recipeListPane = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("recipesearch/resources/RecipeSearch"); // NOI18N
        setTitle(bundle.getString("Application.title")); // NOI18N
        setName("applicationFrame"); // NOI18N

        jSplitPane1.setDividerLocation(160);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sök");

        cuisineComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<ej valt>", "Svergie", "Grekland", "Indien", "Asien", "Afrika", "Frankrike" }));
        cuisineComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuisineComboBoxActionPerformed(evt);
            }
        });

        mainIngredientButtonGroup.add(meatRadioButton);
        meatRadioButton.setText("Kött");
        meatRadioButton.setBorder(null);
        meatRadioButton.setBorderPainted(true);
        meatRadioButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recipesearch/resources/meat_icon.png"))); // NOI18N
        meatRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                meatRadioButtonMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                meatRadioButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                meatRadioButtonMouseEntered(evt);
            }
        });

        mainIngredientButtonGroup.add(fishRadioButton);
        fishRadioButton.setText("Fisk");
        fishRadioButton.setBorder(null);
        fishRadioButton.setBorderPainted(true);
        fishRadioButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recipesearch/resources/fish_icon.png"))); // NOI18N
        fishRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fishRadioButtonMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fishRadioButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fishRadioButtonMouseEntered(evt);
            }
        });

        mainIngredientButtonGroup.add(vegetarianRadioButton);
        vegetarianRadioButton.setText("Vegteriskt");
        vegetarianRadioButton.setBorder(null);
        vegetarianRadioButton.setBorderPainted(true);
        vegetarianRadioButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recipesearch/resources/tree_icon.png"))); // NOI18N
        vegetarianRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                vegetarianRadioButtonMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vegetarianRadioButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                vegetarianRadioButtonMouseEntered(evt);
            }
        });

        mainIngredientButtonGroup.add(chickenRadioButton);
        chickenRadioButton.setText("Kyckling");
        chickenRadioButton.setBorder(null);
        chickenRadioButton.setBorderPainted(true);
        chickenRadioButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recipesearch/resources/Chicken_icon.png"))); // NOI18N
        chickenRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                chickenRadioButtonMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chickenRadioButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                chickenRadioButtonMouseEntered(evt);
            }
        });

        jLabel2.setText("Kök");

        difficulityButtonGroup.add(easyRadioButton);
        easyRadioButton.setText("Lätt");
        easyRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                easyRadioButtonMouseClicked(evt);
            }
        });

        difficulityButtonGroup.add(mediumRadioButton);
        mediumRadioButton.setText("Medel");
        mediumRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mediumRadioButtonMouseClicked(evt);
            }
        });

        difficulityButtonGroup.add(hardRadioButton);
        hardRadioButton.setText("Svårt");
        hardRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hardRadioButtonMouseClicked(evt);
            }
        });

        jLabel3.setText("Max Pris(kr)");

        maxPriceSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(5)));
        maxPriceSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                maxPriceSpinnerStateChanged(evt);
            }
        });

        jLabel4.setText("Max Tid(m)");

        maxTimeSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 150, 10));
        maxTimeSpinner.setToolTipText("");
        maxTimeSpinner.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        maxTimeSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                maxTimeSpinnerStateChanged(evt);
            }
        });

        jLabel5.setText("Huvudingrediens");

        jLabel6.setText("Svårighetsgrad");

        mainIngredientButtonGroup.add(noMainRadioButton);
        noMainRadioButton.setSelected(true);
        noMainRadioButton.setText("Ej valt");
        noMainRadioButton.setBorder(null);
        noMainRadioButton.setBorderPainted(true);
        noMainRadioButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recipesearch/resources/no_choice.png"))); // NOI18N
        noMainRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                noMainRadioButtonMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noMainRadioButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                noMainRadioButtonMouseEntered(evt);
            }
        });

        difficulityButtonGroup.add(noDifficulityRadioButton);
        noDifficulityRadioButton.setSelected(true);
        noDifficulityRadioButton.setText("Ej valt");
        noDifficulityRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noDifficulityRadioButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noDifficulityRadioButton)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(hardRadioButton)
                                .addComponent(mediumRadioButton)
                                .addComponent(easyRadioButton)
                                .addComponent(jLabel6)
                                .addComponent(vegetarianRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                .addComponent(meatRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chickenRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fishRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(noMainRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(cuisineComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(42, 42, 42))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(65, 65, 65))
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(maxPriceSpinner)
                                    .addComponent(maxTimeSpinner))))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cuisineComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(meatRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vegetarianRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chickenRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fishRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noMainRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(easyRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mediumRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hardRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noDifficulityRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(maxPriceSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(maxTimeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        recipeListPane.setLayout(new javax.swing.BoxLayout(recipeListPane, javax.swing.BoxLayout.PAGE_AXIS));
        recipeScrollPane.setViewportView(recipeListPane);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(recipeScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(recipeScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel2);

        java.util.ResourceBundle bundle1 = java.util.ResourceBundle.getBundle("recipesearch/resources/RecipeSearchView"); // NOI18N
        fileMenu.setText(bundle1.getString("fileMenu.text")); // NOI18N

        exitMenuItem.setText(bundle1.getString("exitApplicationMenuItem.text")); // NOI18N
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        jMenuBar1.add(fileMenu);

        helpMenu.setText(bundle1.getString("helpMenu.text")); // NOI18N

        aboutMenuItem.setText(bundle1.getString("aboutMenuItem.text")); // NOI18N
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 906, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        new RecipeSearchAboutBox(this).setVisible(true);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void meatRadioButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_meatRadioButtonMouseEntered
        setMouseOverRadioButton(meatRadioButton);
    }//GEN-LAST:event_meatRadioButtonMouseEntered

    private void vegetarianRadioButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vegetarianRadioButtonMouseEntered
        setMouseOverRadioButton(vegetarianRadioButton);
    }//GEN-LAST:event_vegetarianRadioButtonMouseEntered

    private void chickenRadioButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chickenRadioButtonMouseEntered
        setMouseOverRadioButton(chickenRadioButton);
    }//GEN-LAST:event_chickenRadioButtonMouseEntered

    private void fishRadioButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fishRadioButtonMouseEntered
        setMouseOverRadioButton(fishRadioButton);
    }//GEN-LAST:event_fishRadioButtonMouseEntered

    private void noMainRadioButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noMainRadioButtonMouseEntered
        setMouseOverRadioButton(noMainRadioButton);
    }//GEN-LAST:event_noMainRadioButtonMouseEntered

    private void meatRadioButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_meatRadioButtonMouseExited
        removeMouseOverRadioButton(meatRadioButton);
    }//GEN-LAST:event_meatRadioButtonMouseExited

    private void vegetarianRadioButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vegetarianRadioButtonMouseExited
        removeMouseOverRadioButton(vegetarianRadioButton);
    }//GEN-LAST:event_vegetarianRadioButtonMouseExited

    private void chickenRadioButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chickenRadioButtonMouseExited
        removeMouseOverRadioButton(chickenRadioButton);
    }//GEN-LAST:event_chickenRadioButtonMouseExited

    private void fishRadioButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fishRadioButtonMouseExited
        removeMouseOverRadioButton(fishRadioButton);
    }//GEN-LAST:event_fishRadioButtonMouseExited

    private void noMainRadioButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noMainRadioButtonMouseExited
        removeMouseOverRadioButton(noMainRadioButton);
    }//GEN-LAST:event_noMainRadioButtonMouseExited

    private void maxTimeSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_maxTimeSpinnerStateChanged
		Integer cost = (Integer)maxTimeSpinner.getValue();
		cost += 5;
		cost = (cost/10)*10;
		maxTimeSpinner.setValue(cost);
		
		reportSearch();
    }//GEN-LAST:event_maxTimeSpinnerStateChanged

    private void easyRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_easyRadioButtonMouseClicked
		setActiveDifficulity(easyRadioButton);
		reportSearch();
    }//GEN-LAST:event_easyRadioButtonMouseClicked

    private void mediumRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mediumRadioButtonMouseClicked
        setActiveDifficulity(mediumRadioButton);
		reportSearch();
    }//GEN-LAST:event_mediumRadioButtonMouseClicked

    private void hardRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hardRadioButtonMouseClicked
		setActiveDifficulity(hardRadioButton);
		reportSearch();
    }//GEN-LAST:event_hardRadioButtonMouseClicked

    private void noDifficulityRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noDifficulityRadioButtonMouseClicked
        currentDifficulity = null;
		reportSearch();
    }//GEN-LAST:event_noDifficulityRadioButtonMouseClicked

    private void meatRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_meatRadioButtonMouseClicked
        setActiveMainIngredient(meatRadioButton);
		reportSearch();
    }//GEN-LAST:event_meatRadioButtonMouseClicked

    private void vegetarianRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vegetarianRadioButtonMouseClicked
        setActiveMainIngredient(vegetarianRadioButton);
		reportSearch();
    }//GEN-LAST:event_vegetarianRadioButtonMouseClicked

    private void chickenRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chickenRadioButtonMouseClicked
        setActiveMainIngredient(chickenRadioButton);
		reportSearch();
    }//GEN-LAST:event_chickenRadioButtonMouseClicked

    private void fishRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fishRadioButtonMouseClicked
	setActiveMainIngredient(fishRadioButton);
	reportSearch();
    }//GEN-LAST:event_fishRadioButtonMouseClicked

    private void noMainRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noMainRadioButtonMouseClicked
		setActiveMainIngredient(noMainRadioButton);
		reportSearch();
		currentMainIngredient = null;
    }//GEN-LAST:event_noMainRadioButtonMouseClicked

    private void cuisineComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuisineComboBoxActionPerformed
        reportSearch();
    }//GEN-LAST:event_cuisineComboBoxActionPerformed

    private void maxPriceSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_maxPriceSpinnerStateChanged
        reportSearch();
    }//GEN-LAST:event_maxPriceSpinnerStateChanged

    private void removeMouseOverRadioButton(JRadioButton btn) {
        if (btn == lastClickedRadioButton)
            return;
        btn.setBorder(standardBorder);
    }
    
    private void setMouseOverRadioButton(JRadioButton btn) {
        if (btn == lastClickedRadioButton)
            return;
        btn.setBorder(mouseOverBorder);
    }
    
	private void setActiveDifficulity(JRadioButton btn) {
		currentDifficulity = btn.getText();
	}
	
    private void setActiveMainIngredient(JRadioButton btn) {
        lastClickedRadioButton.setBorder(standardBorder);
        lastClickedRadioButton = btn;
        btn.setBorder(clickedBorder);
		currentMainIngredient = btn.getText();
    }
	
	private void reportSearch() {
		//new SearchFilter(difficulity, maxTime, cuisine, maxPrice, mainIngredient
		//public void reportSearchCriteria(String cuisine, String mainIngredient, String difficulity, int maxPrice, int maxTime) 
		recipeSearchInputs.reportSearchCriteria(
				cuisineComboBox.getSelectedItem().equals("<ej valt>") ? null : (String)cuisineComboBox.getSelectedItem(),
				currentMainIngredient,
				currentDifficulity,
				(int)maxPriceSpinner.getValue(),
				(int)maxTimeSpinner.getValue()
				);
		
	}
	
	public void setRecipeList(List<Recipe> recipeList) {
		
		recipeListPane.removeAll();
		
		for (Recipe r : recipeList) {
			
			recipeListPane.add(new DishPanel(r));
			
		}
		this.revalidate();
	}
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JRadioButton chickenRadioButton;
    private javax.swing.JComboBox cuisineComboBox;
    private javax.swing.ButtonGroup difficulityButtonGroup;
    private javax.swing.JRadioButton easyRadioButton;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JRadioButton fishRadioButton;
    private javax.swing.JRadioButton hardRadioButton;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.ButtonGroup mainIngredientButtonGroup;
    private javax.swing.JSpinner maxPriceSpinner;
    private javax.swing.JSpinner maxTimeSpinner;
    private javax.swing.JRadioButton meatRadioButton;
    private javax.swing.JRadioButton mediumRadioButton;
    private javax.swing.JRadioButton noDifficulityRadioButton;
    private javax.swing.JRadioButton noMainRadioButton;
    private javax.swing.JPanel recipeListPane;
    private javax.swing.JScrollPane recipeScrollPane;
    private javax.swing.JRadioButton vegetarianRadioButton;
    // End of variables declaration//GEN-END:variables
    private final Border standardBorder = BorderFactory.createBevelBorder(BevelBorder.RAISED, java.awt.Color.white, new java.awt.Color(204, 204, 204), java.awt.Color.lightGray, java.awt.Color.darkGray);
    private final Border mouseOverBorder = BorderFactory.createBevelBorder(BevelBorder.RAISED, java.awt.Color.GRAY, new java.awt.Color(250, 250, 250), java.awt.Color.lightGray, java.awt.Color.darkGray);
    private final Border clickedBorder = BorderFactory.createBevelBorder(BevelBorder.LOWERED, java.awt.Color.white, new java.awt.Color(204, 204, 204), java.awt.Color.lightGray, java.awt.Color.darkGray);
	private final IRecipeSearchInputs recipeSearchInputs;
	private JRadioButton lastClickedRadioButton;
	
	private String currentDifficulity = null;
	private String currentMainIngredient = null;
}
